create database soloproject;

use soloproject;

select * from users;
drop table board;
CREATE TABLE users(
	id INT AUTO_INCREMENT PRIMARY KEY,
	userName VARCHAR(50) UNIQUE NOT NULL,
	email VARCHAR(255) UNIQUE NOT NULL,
	password VARCHAR(255) NOT NULL,
	role ENUM('USER', 'ADMIN') NOT NULL DEFAULT 'USER',
	phoneNumber VARCHAR(20) DEFAULT NULL,
	is_Verified TINYINT(1) DEFAULT 0,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE verification_codes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    code VARCHAR(10) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE board(
	boardId INT AUTO_INCREMENT PRIMARY KEY,
	userId INT,
	title VARCHAR(255) NOT NULL,
	content TEXT NOT NULL,
	createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updateAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	views INT DEFAULT 0,
	likes INT DEFAULT 0,
	FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
);